# Generated by Django 3.2.9 on 2022-10-25 19:43

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0002_submittedanswermodel_created_on'),
    ]

    operations = [
        migrations.AddField(
            model_name='exammediamodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='ordermediamodel',
            name='created_on',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
