# Generated by Django 3.2.9 on 2022-10-28 09:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0003_auto_20221025_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='inprogress',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
