# Generated by Django 3.2.9 on 2022-10-28 11:01

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0006_chatmodel_receiver'),
    ]

    operations = [
        migrations.AddField(
            model_name='chatmodel',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.ordermodel'),
            preserve_default=False,
        ),
    ]
