# Generated by Django 3.2.9 on 2022-10-28 19:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0007_chatmodel_parent'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='chatmodel',
            name='is_disabled',
        ),
        migrations.AddField(
            model_name='ordermodel',
            name='is_disabled',
            field=models.BooleanField(blank=True, default=False, null=True),
        ),
    ]
