# Generated by Django 3.2.9 on 2022-10-28 21:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0008_auto_20221028_1940'),
    ]

    operations = [
        migrations.AddField(
            model_name='ordermodel',
            name='messages',
            field=models.IntegerField(blank=True, default=0, null=True),
        ),
    ]
