# Generated by Django 3.2.9 on 2022-10-30 14:24

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('panel', '0012_equipmentmodel_metermodel'),
    ]

    operations = [
        migrations.CreateModel(
            name='ReadingModel',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('meter_name', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_location', models.CharField(blank=True, max_length=100, null=True)),
                ('meter_reading', models.CharField(blank=True, max_length=100, null=True)),
                ('date', models.DateField(blank=True, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'meter_readings_tbl',
                'db_table': 'meter_readings_tbl',
            },
        ),
    ]
