# Generated by Django 3.2.9 on 2022-10-30 14:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('panel', '0013_readingmodel'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='readingmodel',
            name='meter_name',
        ),
        migrations.AddField(
            model_name='readingmodel',
            name='parent',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='panel.metermodel'),
            preserve_default=False,
        ),
    ]
