# Generated by Django 3.2.9 on 2022-09-23 11:49

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('auth', '0012_alter_user_first_name_max_length'),
    ]

    operations = [
        migrations.CreateModel(
            name='SiteModel',
            fields=[
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='auth.user')),
                ('site_name', models.CharField(blank=True, default='Studirre', max_length=100, null=True)),
                ('site_email', models.CharField(blank=True, default='studirre@gmail.com', max_length=100, null=True)),
                ('site_email2', models.CharField(blank=True, default='example@gmail.com', max_length=100, null=True)),
                ('theme_color', models.CharField(blank=True, default='#3d71a1', max_length=100, null=True)),
                ('site_url', models.URLField(blank=True, default='https://studirre.com', null=True)),
                ('description', models.TextField(blank=True, default='Instant access to millions of Study Resources, Course Notes, Test Prep, 24/7 Homework Help, Tutors, and more. Learn, teach, and study with Studirre. Get unstuck.', null=True)),
                ('key_words', models.TextField(blank=True, default='Studirre,', null=True)),
                ('address', models.CharField(blank=True, default='Moi University,Kesses, Eldoret Uasin Gishu County Kenya', max_length=250, null=True)),
                ('location', models.CharField(blank=True, default='Eldoret,Kenya ', max_length=250, null=True)),
                ('phone', phonenumber_field.modelfields.PhoneNumberField(blank=True, default='+254798449624', max_length=128, null=True, region=None, verbose_name='phone')),
                ('working_days', models.CharField(blank=True, default='mon-fri', max_length=250, null=True)),
                ('site_content', models.CharField(blank=True, max_length=250, null=True)),
                ('working_hours', models.CharField(blank=True, default='8am-10pm', max_length=250, null=True)),
                ('closed_days', models.CharField(blank=True, default='sun', max_length=250, null=True)),
                ('special_days', models.CharField(blank=True, default='sat & holidays', max_length=250, null=True)),
                ('special_hours', models.CharField(blank=True, default='sat & holidays', max_length=250, null=True)),
                ('facebook', models.CharField(blank=True, default='https://web.facebook.com/kevy.kibbz/', max_length=250, null=True)),
                ('twitter', models.CharField(blank=True, default='https://twitter.com/Kevin36285655', max_length=250, null=True)),
                ('instagram', models.CharField(blank=True, default='https://www.instagram.com/kevviey/', max_length=250, null=True)),
                ('video_link', models.CharField(blank=True, default='https://youtube.com', max_length=250, null=True)),
                ('whatsapp', models.CharField(blank=True, default='https://wa.link/r9fxm4', max_length=250, null=True)),
                ('linkedin', models.CharField(blank=True, default='https://www.linkedin.com/in/chill-cash-260aba206/', max_length=250, null=True)),
                ('youtube', models.CharField(blank=True, default='https://youtube.com', max_length=250, null=True)),
                ('currency_code', models.CharField(blank=True, default='Ksh', max_length=250, null=True)),
                ('currency_symbol', models.CharField(blank=True, max_length=250, null=True)),
                ('favicon', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('website_logo', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('footer_logo', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('email_template_logo', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('login_logo', models.ImageField(blank=True, default='logos/favicon.ico', null=True, upload_to='logos/')),
                ('number_of_words_per_page', models.IntegerField(blank=True, default=10, null=True)),
                ('no_of_quiz_to_display', models.IntegerField(blank=True, default=3, null=True)),
                ('no_of_correct_ans', models.IntegerField(blank=True, default=1, null=True)),
                ('wallet_limit', models.IntegerField(blank=True, default=1000, null=True)),
                ('min_withdraw', models.IntegerField(blank=True, default=1000, null=True)),
                ('essay_topic', models.CharField(blank=True, max_length=250, null=True)),
                ('commision_percent', models.CharField(blank=True, max_length=250, null=True)),
                ('service_charge', models.CharField(blank=True, max_length=250, null=True)),
                ('quiz_time', models.IntegerField(blank=True, default=30, null=True)),
                ('created_on', models.DateTimeField(default=django.utils.timezone.now)),
            ],
            options={
                'verbose_name_plural': 'site_model',
                'db_table': 'site_model',
            },
        ),
    ]
