# Generated by Django 3.2.9 on 2022-10-09 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='sitemodel',
            name='is_installed',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='main',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='sitemodel',
            name='timezone',
            field=models.CharField(blank=True, default='Africa/Nairobi', max_length=200, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='commision_percent',
            field=models.CharField(blank=True, default='20', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='currency_symbol',
            field=models.CharField(blank=True, default='Ksh', max_length=250, null=True),
        ),
        migrations.AlterField(
            model_name='sitemodel',
            name='service_charge',
            field=models.CharField(blank=True, default='20', max_length=250, null=True),
        ),
    ]
