# Generated by Django 3.2.9 on 2022-10-12 08:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('installation', '0002_auto_20221009_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='sitemodel',
            name='essay_topic',
            field=models.CharField(blank=True, default='AgroForestry', max_length=250, null=True),
        ),
    ]
